config/routes.rb
Rails.application.routes.draw do

  #登録系で使うデバイスのルーティングを先に書く
  devise_for :admin, skip: [:registrations, :passwords], controllers: {  #新規登録とパス変更は使わない
    sessions: "admin/sessions"  #管理者が使うのはログインだけ
  }
  devise_for :customers,skip: [:passwords], controllers: {  #パス変更は使わない
    registrations: "public/registrations",
    sessions: 'public/sessions'  #ユーザーが使うのは新規登録とログイン
  }

  #ゲストログインのルーティング
  devise_scope :customer do
    post 'customer/guest_sign_in', to:'public/sessions#guest_sign_in'
  end

  #publicのルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    get '/customers', to:'customers#index', as:'customers_index'  #「/customers」 = homes#index:customers_index_path
    get 'customers/my_page', to:'customers#show', as:'my_page'  #「/customers/my_page」 = customers#show:my_page_path 自分のshow
    resources :customers, only: [:show] do  #「/customers/:id」 = customers#show:customer_path 他人のshow
      collection do
        get 'my_page/edit', to:'customers#edit', as:'edit_my_page'  #「/customers/my_page/edit」 = customers#edit:edit_my_page_path
        patch 'information', to:'customers#update', as:'update_information'  #「/customers/information」 = customers#update:update_information_path patchアクション
        delete 'out'  #「/customers/out」 = customers#out outアクション
      end
      member do
        get 'favorite'  #「/customers/:id/favorite」 = customers#favorite
        resource :relationships, only: [:create, :destroy]  #「/customers/:id/relationships」 = relationships#create&destroy:relationships_path
          get "follower_customer" => "relationships#follower_customer", as:"follower"  #「/customers/:id/follower_customer」 = relationships#follower_customer:follower_customer_path
          get "followed_customer" => "relationships#followed_customer", as:"followed"  #「/customers/:id/followed_customer」 = relationships#followed_customer:followed_customer_path
      end  #↑resources :customers, only: [:show] doの中に設定されているので、as:follower_pathではなく_customerも含まれる
    end
    resources :ideas, only: %i[new create edit update destroy] do
      resource :favorites, only: %i[create destroy]
    end
    resources :favorites, only: [] do
      get 'favorite_customers', on: :member, to: 'favorites#favorite_customers', as: 'customers'
    end
    resources :tags, only: [:index, :show]
    get "/search", to: "searches#search"
  end

  #adminのルーティング
  get 'admin', to:'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:edit, :update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image

  #アソシエーション
  has_many :ideas, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_customer, through: :follower, source: :followed
  has_many :followed_customer, through: :followed, source: :follower

  #バリデーション
  validates :profile_image, content_type: { in: ['image/jpg','image/jpeg','image/png'], message: 'はJPGかPNG形式で登録してください' }  #jpegとpngを許可(jpgはWindowsでのファイル名制限から生まれた短縮形)
  validates :name, presence: true
  validates :preference, presence: true
  validates :weak, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP }  #URI=Rubyの定型でメアドを検証して、一般的な形式(format)以外をはじくバリデーション

  #検索用メソッド
  def self.search_for(word, method)
    if method == 'perfect'
      Customer.where("name LIKE ?", "#{word}")
    elsif method == 'forward'
      Customer.where("name LIKE ?", "#{word}%")
    elsif method == 'backward'
      Customer.where("name LIKE ?", "%#{word}")
    else
      Customer.where("name LIKE ?", "%#{word}%")
    end
  end

  #ゲストユーザーを設定
  GUEST_USER_EMAIL = "guest@example.com" #メールアドレスの変数定義
  def self.guest #
    find_or_create_by!(email: GUEST_USER_EMAIL) do |customer| #メールがゲストメールのユーザーがいなければ作成する
      customer.password = SecureRandom.urlsafe_base64 #パスワードはランダム生成
      customer.name = 'ゲスト'
      customer.preference = 'ゲストはTOPとaboutしか触れない' #遷移不可ページでしか見られないが、バリデーションに引っかかるので必要
      customer.weak = 'ゲストはTOPとaboutしか触れない' #遷移不可ページでしか見られないが、バリデーションに引っかかるので必要
      customer.is_active = true
    end
  end

  #メールアドレスの正規化をバリデーションチェックの前に行う
  before_validation :normalize_email  #↓privateで定義

  #ユーザーがログイン済みかどうか確認するメソッド
  def active_for_authentication?
    super && is_active? #deviseの認証OKかつis_activeが真(true)であること
  end

  #フォロー機能用のメソッド
  def follow(customer)  #customerをフォローするメソッド
    follower.create(followed_id: customer.id)  #フォロワーを作ってcustomeridと紐づける
  end
  def unfollow(customer)  #フォローを解除するメソッド
    follower.find_by(followed_id: customer.id).destroy  #フォロワーを探して削除する
  end
  def following?(customer)  #フォローしているか確認するメソッド
    follower_customer.include?(customer)  #follower_customerにcustomerが含まれているか確認
  end
  def follower_customers  # フォロワーを取得するメソッド
    Customer.joins(:follower)  #customerとfollowerのテーブルを結合する
            .where(follower: { followed_id: id, is_active: true }) # followerの中でアクティブなユーザーのみを含める
  end
  def followed_customers  # フォローしているユーザーを取得するメソッド
    Customer.joins(:followed)  #customerとfollowedのテーブルを結合する
            .where(followed: { follower_id: id, is_active: true }) # followedの中でアクティブなユーザーのみを含める
  end

  #プロフィール画像表示用メソッド(幅,高さを引数で渡せる)
  def get_profile_image(width, height)
    unless profile_image.attached?  #profile_imageがある、ではない場合=画像が無い場合の処理
      file_path = Rails.root.join('app/assets/images/no_image.jpg') #使用する画像のパスをfile_pathに代入
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg') #画像を紐づける(file_pathを開いて、no_image.jpgという名前の画像をjpegで添付する)
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end #引数指定のみでリサイズ無しだと、引数に対して登録画像のサイズがかけ離れている場合レイアウトが崩れるのでセットで設定する

  private

  def normalize_email  #メールアドレスが存在する場合、小文字に直して前後の空白を取り除いてself.emailに格納
    self.email = email.downcase.strip if email.present?
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :customer_notview!
  before_action :admin_login!

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update!(customer_params)  #!=失敗したら、falseを返すのではなく処理を中断してエラーを返すだけでいいのでif分岐ではなく[!]で対応
    flash[:notice] = "ステータスを切り替えました！"
    redirect_to edit_admin_customer_path
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :profile_image, :preference, :weak, :is_active)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= stylesheet_link_tag 'admin/customers' %>
<div class="container">

  <div class="row">
    <%= display_flash_messages %> <!--ヘルパーメソッドで指定-->
  </div>

  <div class="row">
    <table>
      <tbody>
        <tr>
          <td>
            <div class="profile-container">
              <%= image_tag @customer.get_profile_image(80, 80), class: 'profile-image' %>
                <div class="profile-name">
                  <span><%= @customer.name %></span>
                </div>
            </div>
          </td>
          <td><%= "アイデア数：#{@customer.ideas.count}個" %></td>
          <td>
            <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
              <%= f.radio_button :is_active, true, id: "active" %> <!--is_activeがtrueであるラジオボタンを作成-->
              <%= f.label :is_active, "有効", for: "active" %> <!--ラジオボタンとセットで記述する　id:activeで紐づけて文字クリックでも有効にできる-->
              <%= f.radio_button :is_active, false, id: "inactive" %>
              <%= f.label :is_active, "退会", for: "inactive" %>
              <%= f.submit "切り替える", data: { confirm: "本当に切り替えますか？" }, class: "btn btn-secondary" %> <!--確認メッセージを挟む-->
            <% end %>
          </td>
        </tr>
        <tr>
          <td>  <!--フォロー人数にはステータスが有効のユーザーのみ含める-->
            <%= "フォロー：#{@customer.follower_customer.where(is_active: true).count}人" %>
          </td>
          <td>
            <%= "フォロワー：#{@customer.followed_customer.where(is_active: true).count}人" %>
          </td>
          <td>  <!--お気に入りがあるか確認　?=有りなら個数表示　:=無しならお気に入り無し表示-->
            <%= @customer.favorites.present? ? "お気に入りアイデア数：#{@customer.favorites.count}個" : "お気に入り無し" %>
          </td>
        </tr>
        <tr>
          <td colspan=3>好物</td>
        </tr>
        <tr>
          <td colspan="3" class="preference-style"><%= content_tag(:div, @customer.preference, class: "scroll") %></td>
        </tr>
        <tr>
          <td colspan=3>苦手</td>
        </tr>
        <tr>
          <td colspan="3" class="preference-style"><%= content_tag(:div, @customer.weak, class: "scroll") %></td>
        </tr>
      </tbody>
    </table>
  </div>

</div>