config/routes.rb
Rails.application.routes.draw do

  #登録系で使うデバイスのルーティングを先に書く
  devise_for :admin, skip: [:registrations, :passwords], controllers: {  #新規登録とパス変更は使わない
    sessions: "admin/sessions"  #管理者が使うのはログインだけ
  }
  devise_for :customers,skip: [:passwords], controllers: {  #パス変更は使わない
    registrations: "public/registrations",
    sessions: 'public/sessions'  #ユーザーが使うのは新規登録とログイン
  }

  #ゲストログインのルーティング
  devise_scope :customer do
    post 'customer/guest_sign_in', to:'public/sessions#guest_sign_in'
  end

  #publicのルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    get '/customers', to:'customers#index', as:'customers_index'  #「/customers」 = homes#index:customers_index_path
    get 'customers/my_page', to:'customers#show', as:'my_page'  #「/customers/my_page」 = customers#show:my_page_path 自分のshow
    resources :customers, only: [:show] do  #「/customers/:id」 = customers#show:customer_path 他人のshow
      collection do
        get 'my_page/edit', to:'customers#edit', as:'edit_my_page'  #「/customers/my_page/edit」 = customers#edit:edit_my_page_path
        patch 'information', to:'customers#update', as:'update_information'  #「/customers/information」 = customers#update:update_information_path patchアクション
        delete 'out'  #「/customers/out」 = customers#out outアクション
      end
      member do
        get 'favorite'  #「/customers/:id/favorite」 = customers#favorite
        resource :relationships, only: [:create, :destroy]  #「/customers/:id/relationships」 = relationships#create&destroy:relationships_path
          get "follower_customer" => "relationships#follower_customer", as:"follower"  #「/customers/:id/follower_customer」 = relationships#follower_customer:follower_customer_path
          get "followed_customer" => "relationships#followed_customer", as:"followed"  #「/customers/:id/followed_customer」 = relationships#followed_customer:followed_customer_path
      end  #↑resources :customers, only: [:show] doの中に設定されているので、as:follower_pathではなく_customerも含まれる
    end
    resources :ideas, only: %i[new create edit update destroy] do
      resource :favorites, only: %i[create destroy]
    end
    resources :favorites, only: [] do
      get 'favorite_customers', on: :member, to: 'favorites#favorite_customers', as: 'customers'
    end
    resources :tags, only: [:index, :show]
    get "/search", to: "searches#search"
  end

  #adminのルーティング
  get 'admin', to:'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:edit, :update]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :customer_notview!
  before_action :admin_login!

  def top
    @customers = Customer.all.page(params[:page]).per(4)  #ユーザー一覧をページネーションする
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<%= stylesheet_link_tag 'admin/homes' %>
<div class="container">

  <div class="row">
    <%= display_flash_messages %> <!--ヘルパーメソッドで指定-->
  </div>

  <div class="row">
    <h1>ユーザー一覧</h1>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>ユーザー</th>
          <th>ステータス</th>
          <th>アドレス</th>
          <th>最新編集</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to edit_admin_customer_path(customer.id), class: 'link-button' do %>
                <div class="profile-container">
                  <%= image_tag customer.get_profile_image(50, 50), class: 'profile-image' %>
                  <div class="profile-name">
                    <span><%= customer.name %></span>
                  </div>
                </div>
              <% end %>
            </td>
            <td>  <!--?で真偽値を判定 is_activeカラムはtrueかfalseで判断するので、trueなら有効falseなら退会を表示が使える-->
              <%= customer.is_active ? "有効" : "退会" %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <% latest_idea = customer.ideas.order(updated_at: :desc).first %>  <!--全ての投稿をorderメソッドでupdated_atで降順(desc)に並べ替えて、最新の投稿を特定-->
              <% if latest_idea.present? %>  <!--最新の投稿があったら-->
                <%= latest_idea.updated_at.in_time_zone('Tokyo').strftime('%Y-%m-%d %H:%M:%S') %>  <!--更新日を日本時間で表示-->
              <% else %>  <!--最新の投稿が無い＝1度も投稿していない-->
                <%= '1度も投稿していません' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <%= paginate @customers, class: "pagination" %> <!--ページネーション-->
  </div>
</div>