config/routes.rb
Rails.application.routes.draw do

  #登録系で使うデバイスのルーティングを先に書く
  devise_for :admin, skip: [:registrations, :passwords], controllers: {  #新規登録とパス変更は使わない
    sessions: "admin/sessions"  #管理者が使うのはログインだけ
  }
  devise_for :customers,skip: [:passwords], controllers: {  #パス変更は使わない
    registrations: "public/registrations",
    sessions: 'public/sessions'  #ユーザーが使うのは新規登録とログイン
  }

  #ゲストログインのルーティング
  devise_scope :customer do
    post 'customer/guest_sign_in', to:'public/sessions#guest_sign_in'
  end

  #publicのルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    get '/customers', to:'customers#index', as:'customers_index'  #「/customers」 = homes#index:customers_index_path
    get 'customers/my_page', to:'customers#show', as:'my_page'  #「/customers/my_page」 = customers#show:my_page_path 自分のshow
    resources :customers, only: [:show] do  #「/customers/:id」 = customers#show:customer_path 他人のshow
      collection do
        get 'my_page/edit', to:'customers#edit', as:'edit_my_page'  #「/customers/my_page/edit」 = customers#edit:edit_my_page_path
        patch 'information', to:'customers#update', as:'update_information'  #「/customers/information」 = customers#update:update_information_path patchアクション
        delete 'out'  #「/customers/out」 = customers#out outアクション
      end
      member do
        get 'favorite'  #「/customers/:id/favorite」 = customers#favorite
        resource :relationships, only: [:create, :destroy]  #「/customers/:id/relationships」 = relationships#create&destroy:relationships_path
          get "follower_customer" => "relationships#follower_customer", as:"follower"  #「/customers/:id/follower_customer」 = relationships#follower_customer:follower_customer_path
          get "followed_customer" => "relationships#followed_customer", as:"followed"  #「/customers/:id/followed_customer」 = relationships#followed_customer:followed_customer_path
      end  #↑resources :customers, only: [:show] doの中に設定されているので、as:follower_pathではなく_customerも含まれる
    end
    resources :ideas, only: %i[new create edit update destroy] do
      resource :favorites, only: %i[create destroy]
    end
    resources :favorites, only: [] do
      get 'favorite_customers', on: :member, to: 'favorites#favorite_customers', as: 'customers'
    end
    resources :tags, only: [:index, :show]
    get "/search", to: "searches#search"
  end

  #adminのルーティング
  get 'admin', to:'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:edit, :update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>アイデアノート</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/186a26f36d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if customer_signed_in? %>
        <h1><%= link_to "<i class='fa-solid fa-book-open'></i> アイデアノート".html_safe, root_path, class: 'logo' %></h1>
        <div class="current_customer">
          <%= image_tag(current_customer.get_profile_image(50, 50)) %>
          <strong><%= current_customer.name %></strong>
        </div>
        <div>
          <ul class="nav nav-pills nav-justified">
            <li><%= link_to "about", about_path, class: "nav-link" %></li>
            <li><%= link_to "マイページ", my_page_path, class:"nav-link" %></li>
            <li><%= link_to "新規投稿", new_idea_path, class: "nav-link" %></li>
            <li><%= link_to "ユーザー一覧", customers_index_path, class: "nav-link" %></li>
            <li><%= link_to "タグ一覧", tags_path, class: "nav-link" %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, class:"nav-link", method: :delete %></li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>
        <h1><%= link_to "<i class='fa-solid fa-book-open'></i> アイデアノート".html_safe, admin_path, class: 'logo' %></h1>
        <div>
          <ul class="nav nav-pills nav-justified">
            <li><%= link_to "ユーザー一覧", admin_path, class: "nav-link" %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
          </ul>
        </div>
      <% else %>
        <h1><%= link_to "<i class='fa-solid fa-book-open'></i> アイデアノート".html_safe, root_path, class: 'logo' %></h1>
        <div>
          <ul class="nav nav-pills nav-justified">
            <li><%= link_to "About", about_path, class:"nav-link" %></li>
            <li><%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %></li>
            <li><%= link_to "ログイン", new_customer_session_path, class:"nav-link" %></li>
          </ul>
        </div>
      <% end %>
    </header>
    <main>
      <% if customer_signed_in? && !guest_user_signed_in? %>  <!--ログインしているかつゲストではない時に表示-->
        <div class="search-form">  <!--↑guest_user_signed_in?はapplication_controllerで定義しているメソッド-->
          <%= render "public/searches/form" %>
        </div>
      <% end%>
      <%= yield %>
    </main>
    <footer>
      <h4>© 2024  アイデアノート</h4>
    </footer>
  </body>
</html>